/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QUIZ_H_RPCGEN
#define _QUIZ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct assignId {
	int clientId;
};
typedef struct assignId assignId;

struct clientSend {
	int clientId;
	int option;
};
typedef struct clientSend clientSend;

struct clientAns {
	int clientId;
	char answer[100];
};
typedef struct clientAns clientAns;

struct serverEvaluate {
	int correct;
};
typedef struct serverEvaluate serverEvaluate;

struct serverQuiz {
	char question[250];
	char option[100];
};
typedef struct serverQuiz serverQuiz;

struct rank {
	int sessionRank;
	int globalRank;
};
typedef struct rank rank;

struct credentials {
	int clientId;
	char password[10];
};
typedef struct credentials credentials;

#define ASSIGNMENT 0x13451111
#define ASSIGNMENTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETID 1
extern  assignId * getid_1(credentials *, CLIENT *);
extern  assignId * getid_1_svc(credentials *, struct svc_req *);
#define GETQUESTION 2
extern  serverQuiz * getquestion_1(clientSend *, CLIENT *);
extern  serverQuiz * getquestion_1_svc(clientSend *, struct svc_req *);
#define EVALUATEANSWER 3
extern  serverEvaluate * evaluateanswer_1(clientAns *, CLIENT *);
extern  serverEvaluate * evaluateanswer_1_svc(clientAns *, struct svc_req *);
#define GETSCORE 4
extern  serverEvaluate * getscore_1(clientSend *, CLIENT *);
extern  serverEvaluate * getscore_1_svc(clientSend *, struct svc_req *);
#define GETRANK 5
extern  rank * getrank_1(clientSend *, CLIENT *);
extern  rank * getrank_1_svc(clientSend *, struct svc_req *);
#define EXIT 6
extern  serverEvaluate * exit_1(clientSend *, CLIENT *);
extern  serverEvaluate * exit_1_svc(clientSend *, struct svc_req *);
#define LOGIN 7
extern  serverEvaluate * login_1(credentials *, CLIENT *);
extern  serverEvaluate * login_1_svc(credentials *, struct svc_req *);
extern int assignment_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETID 1
extern  assignId * getid_1();
extern  assignId * getid_1_svc();
#define GETQUESTION 2
extern  serverQuiz * getquestion_1();
extern  serverQuiz * getquestion_1_svc();
#define EVALUATEANSWER 3
extern  serverEvaluate * evaluateanswer_1();
extern  serverEvaluate * evaluateanswer_1_svc();
#define GETSCORE 4
extern  serverEvaluate * getscore_1();
extern  serverEvaluate * getscore_1_svc();
#define GETRANK 5
extern  rank * getrank_1();
extern  rank * getrank_1_svc();
#define EXIT 6
extern  serverEvaluate * exit_1();
extern  serverEvaluate * exit_1_svc();
#define LOGIN 7
extern  serverEvaluate * login_1();
extern  serverEvaluate * login_1_svc();
extern int assignment_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_assignId (XDR *, assignId*);
extern  bool_t xdr_clientSend (XDR *, clientSend*);
extern  bool_t xdr_clientAns (XDR *, clientAns*);
extern  bool_t xdr_serverEvaluate (XDR *, serverEvaluate*);
extern  bool_t xdr_serverQuiz (XDR *, serverQuiz*);
extern  bool_t xdr_rank (XDR *, rank*);
extern  bool_t xdr_credentials (XDR *, credentials*);

#else /* K&R C */
extern bool_t xdr_assignId ();
extern bool_t xdr_clientSend ();
extern bool_t xdr_clientAns ();
extern bool_t xdr_serverEvaluate ();
extern bool_t xdr_serverQuiz ();
extern bool_t xdr_rank ();
extern bool_t xdr_credentials ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QUIZ_H_RPCGEN */
