/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "quiz.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
assignment_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		credentials getid_1_arg;
		clientSend getquestion_1_arg;
		clientAns evaluateanswer_1_arg;
		clientSend getscore_1_arg;
		clientSend getrank_1_arg;
		clientSend exit_1_arg;
		credentials login_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GETID:
		_xdr_argument = (xdrproc_t) xdr_credentials;
		_xdr_result = (xdrproc_t) xdr_assignId;
		local = (char *(*)(char *, struct svc_req *)) getid_1_svc;
		break;

	case GETQUESTION:
		_xdr_argument = (xdrproc_t) xdr_clientSend;
		_xdr_result = (xdrproc_t) xdr_serverQuiz;
		local = (char *(*)(char *, struct svc_req *)) getquestion_1_svc;
		break;

	case EVALUATEANSWER:
		_xdr_argument = (xdrproc_t) xdr_clientAns;
		_xdr_result = (xdrproc_t) xdr_serverEvaluate;
		local = (char *(*)(char *, struct svc_req *)) evaluateanswer_1_svc;
		break;

	case GETSCORE:
		_xdr_argument = (xdrproc_t) xdr_clientSend;
		_xdr_result = (xdrproc_t) xdr_serverEvaluate;
		local = (char *(*)(char *, struct svc_req *)) getscore_1_svc;
		break;

	case GETRANK:
		_xdr_argument = (xdrproc_t) xdr_clientSend;
		_xdr_result = (xdrproc_t) xdr_rank;
		local = (char *(*)(char *, struct svc_req *)) getrank_1_svc;
		break;

	case EXIT:
		_xdr_argument = (xdrproc_t) xdr_clientSend;
		_xdr_result = (xdrproc_t) xdr_serverEvaluate;
		local = (char *(*)(char *, struct svc_req *)) exit_1_svc;
		break;

	case LOGIN:
		_xdr_argument = (xdrproc_t) xdr_credentials;
		_xdr_result = (xdrproc_t) xdr_serverEvaluate;
		local = (char *(*)(char *, struct svc_req *)) login_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (ASSIGNMENT, ASSIGNMENTVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, ASSIGNMENT, ASSIGNMENTVERS, assignment_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (ASSIGNMENT, ASSIGNMENTVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, ASSIGNMENT, ASSIGNMENTVERS, assignment_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (ASSIGNMENT, ASSIGNMENTVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
