/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "quiz.h"

bool_t
xdr_assignId (XDR *xdrs, assignId *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->clientId))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clientSend (XDR *xdrs, clientSend *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->clientId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->option))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_clientAns (XDR *xdrs, clientAns *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->clientId))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->answer, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_serverEvaluate (XDR *xdrs, serverEvaluate *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->correct))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_serverQuiz (XDR *xdrs, serverQuiz *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->question, 250,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->option, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rank (XDR *xdrs, rank *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->sessionRank))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->globalRank))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_credentials (XDR *xdrs, credentials *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->clientId))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
