/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "quiz.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

assignId *
getid_1(credentials *argp, CLIENT *clnt)
{
	static assignId clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETID,
		(xdrproc_t) xdr_credentials, (caddr_t) argp,
		(xdrproc_t) xdr_assignId, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

serverQuiz *
getquestion_1(clientSend *argp, CLIENT *clnt)
{
	static serverQuiz clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETQUESTION,
		(xdrproc_t) xdr_clientSend, (caddr_t) argp,
		(xdrproc_t) xdr_serverQuiz, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

serverEvaluate *
evaluateanswer_1(clientAns *argp, CLIENT *clnt)
{
	static serverEvaluate clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EVALUATEANSWER,
		(xdrproc_t) xdr_clientAns, (caddr_t) argp,
		(xdrproc_t) xdr_serverEvaluate, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

serverEvaluate *
getscore_1(clientSend *argp, CLIENT *clnt)
{
	static serverEvaluate clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETSCORE,
		(xdrproc_t) xdr_clientSend, (caddr_t) argp,
		(xdrproc_t) xdr_serverEvaluate, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rank *
getrank_1(clientSend *argp, CLIENT *clnt)
{
	static rank clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETRANK,
		(xdrproc_t) xdr_clientSend, (caddr_t) argp,
		(xdrproc_t) xdr_rank, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

serverEvaluate *
exit_1(clientSend *argp, CLIENT *clnt)
{
	static serverEvaluate clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXIT,
		(xdrproc_t) xdr_clientSend, (caddr_t) argp,
		(xdrproc_t) xdr_serverEvaluate, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

serverEvaluate *
login_1(credentials *argp, CLIENT *clnt)
{
	static serverEvaluate clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LOGIN,
		(xdrproc_t) xdr_credentials, (caddr_t) argp,
		(xdrproc_t) xdr_serverEvaluate, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
